### ISSUE TITLE
Keine Begrenzung bei der Anzahl

### ISSUE THREAD

**Issue by 12Jacky** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#15]
- es kann ab einer Person losgehen

**Comment by 12Jacky** [comment]
Update: 29.05 

Wir haben Grenzen bekommen und damit hätte ich das Ticket geschlossen. Oder Willst du hier unsere Begrenzungen die wir Beachten müssen Reinschreiben, beheben und dann schließen

**Comment by Abdullah-C58** [comment]
Ich hätte für die Begrenzungen die wir beachten müssen auch eigene Tickets erstellt. 
Somit schließe ich dann das Ticket hier.
