### ISSUE TITLE
Multiple choice

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#16]
Antwortmöglichkeiten

**Comment by 12Jacky** [comment]
Ist momentan bei den anderen nicht möglich, vielleicht können sie den Fehler beheben

**Comment by 12Jacky** [comment]
Der Fehler wurde behoben, die Multiple Choice antworten können jetzt generiert werden müssen nur bei den Diagrammen gerade bei so etwas wie der Heatmap bewusst kontrolliert werden ob es funktioniert bei der Anzeige, nicht das er eine von vielen Antworten nimmt oder keine .
