### ISSUE TITLE
Testumfrage erstellen

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#19]
Mit Testdaten
In der H2 Datenbank (Treffen mit den anderen)

**Comment by 12Jacky** [comment]
Hätte bevor wir uns mit den anderen Treffen hingesetzt und geschaut was wir haben wollen und das dann einfach mal Notiert. So haben wir etwas vorbereitet und können wo wir sagen da könnten Fehler entstehen gleich mit reinbauen

**Comment by Abdullah-C58** [comment]
Ja da stimme ich dir zu. Wir können die Woche ein Call ansetzen

**Comment by Abdullah-C58** [comment]
Testumfrage zu erstellen ist nicht mehr notwendig, da wir die Datenbank von Team 1 direkt verwenden werden um zu testen.
