### ISSUE TITLE
Storyboard erstellen

### ISSUE THREAD

**Issue by 12Jacky** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#21]
AUs dem StoryBoard können dann die Konkreten Anforderungen erstellt werden.
Storyboard in ein geteiltes OneNote zwischen uns erstellen

**Comment by Abdullah-C58** [comment]
Storyboard in geteilter OneNote erstellt

**Comment by 12Jacky** [comment]
Im storyboard ist eine falsche Reihenfolge die behoben werden muss davor ist das Ticket nicht zu schließen

**Comment by Abdullah-C58** [comment]
Upgedated in OneNote
