### ISSUE TITLE
Technologietest erstellen

### ISSUE THREAD

**Issue by 12Jacky** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#27]
Technologietest - probieren Sie tatsächlich etwas aus, das Ihnen hilft zu entscheiden, welche Technologie(n) Sie einsetzen wollen.

**Comment by 12Jacky** [comment]
Fehlerhaft und kann so nicht geschlossen werden. Wir haben von VisualStudio in RStudio gewechselt und nicht die Sprachen

**Comment by Abdullah-C58** [comment]
Anders war es auch nicht definiert. Außerdem ist die auch schon umgeändert worden.
