### ISSUE TITLE
Erste Testanalyse erstellen

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#28]
Excel Test zur Anzeige

**Comment by 12Jacky** [comment]
[Test Exceltabelle.xlsx](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/files/15333322/Test.Exceltabelle.xlsx)
