### ISSUE TITLE
Testdatenbank erstellen 

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#37]

**Comment by 12Jacky** [comment]
Hoffe du kannst es öffnen
[Test Exceltabelle.xlsx](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/files/15178575/Test.Exceltabelle.xlsx)
