### ISSUE TITLE
Heatmap erstellen

### ISSUE THREAD

**Issue by 12Jacky** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#50]
https://technavigator.de/wiki/heatmap/

Schlüsselerkenntnisse:
Heatmaps sind ein wirksames Tool zur Analyse und Visualisierung von Daten in der Webanalyse.
Sie ermöglichen eine einfache Auswertung des Nutzerverhaltens durch farbkodierte Darstellungen von Klicks, Scrolls und Mausbewegungen.
Heatmaps können genutzt werden, um das Design einer Website zu optimieren, die Benutzerfreundlichkeit zu verbessern und die Conversion-Rate zu erhöhen.
Mit Heatmap-Tools wie Hotjar können wertvolle Erkenntnisse gewonnen werden, die bei der Entscheidungsfindung und dem Setzen von Prioritäten helfen.

**Comment by 12Jacky** [comment]
Heatmap ist erstellt, ich habe nur um die Heatmap noch kästen, wo ich momentan nicht weiß wie die weg gehen

**Comment by 12Jacky** [comment]
Fehler ist behoben

**Comment by Abdullah-C58** [comment]
Kästen sind noch zu sehen
<img width="630" alt="Bildschirmfoto 2024-05-28" src="https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/167157159/6f8f35a0-1cd0-43fc-9c9b-d04d09e8ab64">

**Comment by Abdullah-C58** [comment]
Neue Code im "Pull Request" zu sehen:
https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/pull/53

Mit dem aktualisierten Code sieht es wie folgt aus:
<img width="635" alt="Bildschirmfoto 2024-05-28(1)" src="https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/167157159/b64b3415-cb9f-4ff2-aa25-871eedced1c5">

**Comment by 12Jacky** [comment]
Kleiner Tipp Aktualisiere Vielleicht die codes und auch was ich geändert habe, dann wüsstest du das die Kasten nicht mehr da gewesen sind

**Comment by Abdullah-C58** [comment]
Du solltest überprüfen welchen Code du hochlädst. Vermutlich hast du den falschen Code hochgeladen. Der Screenshot ist vor 1 Stunde gemacht worden.

**Comment by Abdullah-C58** [comment]
Ok. Du hast im Call nichts dazu gesagt als ich erzählt habe, dass ich es gefixt habe. Darüber hinaus habe ich im Code ggplot2 verwendet, dadurch ist die Visualisierung noch besser .

**Comment by 12Jacky** [comment]
![Screenshot 2024-05-28 235154](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/166836065/ca21d8dc-7fd8-4aa4-93e6-c48c4469aa5d)

Das liegt vielleicht daran das du am Anfang behauptet hast du hast die Heatmap erstellt was ja nicht stimmt und außerdem bin ich in den Call nicht dazu gekommen, da er abgebrochen wurde
