### ISSUE TITLE
Median Objektfehler

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#54]
<img width="773" alt="Bildschirmfoto 2024-05-28(2)" src="https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/167157159/335a6fb8-74eb-497d-b3cb-3a8dd20d4823">

'x3' soll für die Visualisierung des Medians verwendet werden.
Vermutlich sollte 'x3' eine Variable sein, die für das Histogramm verwendet wird, aber sie wurde nicht erstellt.

**Comment by Abdullah-C58** [comment]
https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/commit/e809bbecaab1db6f27cd65ac1f3b108345a45fa0

Variable erstellt mit Beispiel-Daten. Jetzt werden zumindest Daten angezeigt.
<img width="1417" alt="Bildschirmfoto 2024-05-28(5)" src="https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/167157159/2bb91d08-0731-4d65-b849-e048912b7a0c">

**Comment by 12Jacky** [comment]
Ok danke fürs Ausbessern
