### ISSUE TITLE
GGplot 2 Fehler

### ISSUE THREAD

**Issue by 12Jacky** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#56]
Hast du mal dein Ganzes Projekt geschlossen und wieder geöffnet?
Mir ist aufgefallen wenn ich das mache und dann ggplot 2 im Code verwendet habe, das dann Fehler auftreten wenn man das ein paarmal macht.  Sollte der Selbe Fehler bei dir auftreten  müssen wir das berücksichtigen. Was auch der Grund war warum ich meist das ggplot 2 rausgebaut habe. 
Damit besteht die Chance das es nicht gehen könnte bei anderen.

**Comment by Abdullah-C58** [comment]
Ja, bei mir kommen da keine Fehler. Wäre gut wenn du den genauen Fehler hier teilen würdest, dann kann 
ich es mir genauer anschauen.

**Comment by 12Jacky** [comment]
Stelle ich dir rein wenn ich Ihn wieder habe

**Comment by 12Jacky** [comment]
Der Fehler von ggplot2 kam daher, das er mir es ständig im Hintergrund deinstalliert hatte. Habe es geschafft das er dies nicht mehr tut. Und damit schließe ich das Ticket. Kommt wieder ein Fehler wird dieses Ticket geöffnet
