### ISSUE TITLE
MVP klar definieren

### ISSUE THREAD

**Issue by 12Jacky** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#57]
Im Wiki einen Eintrag mit 
- was ist ein MVP
- Was konkret ist unser MVP

**Comment by Abdullah-C58** [comment]
https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/wiki/Minimum-Viable-Product

Ich schließe hiermit das Issue. Falls du Änderungen vornehmen möchtest, kannst du es wieder öffnen.
