### ISSUE TITLE
Architekturmodell erstellen

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#58]
Für die Dokumentation im Wiki

**Comment by 12Jacky** [comment]
Für die Dokumentation im Wiki sollen alle Pages, die wir im schnellen Überblick haben wollen auf der rechten Seite angezeigt werden. Es wäre super wenn ich auf das Wort gehe und sie dann mit den Richtigen Link aufrufen kann.

**Comment by 12Jacky** [comment]
![image](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/166836065/77633a74-a083-4cf2-bb2c-3837a7ddae9e)
