### ISSUE TITLE
An die PostreSQL-Datenbank von Team 1 anbinden

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#59]
Im ersten Schritt die Datenbank von Team 1 Integrieren und testen ob der Import funktioniert.
Überlegen wie genau das gehen soll, z.B File-basiert oder free hosting ?

**Comment by a71na** [comment]
Hallo Ihr beiden, damit Ihr schon einmal Bescheid wisst: Die neue Datenbank steht, ich habe mich bewusst für die PostgreSQL-Datenbank entschieden. Kann gern am Dienstag mehr dazu sagen. An sich sollte es aber keine großen Auswirkungen haben.

Der Commit folgt morgen, wenn ich das Passwort sicher verwahrt habe. Möchte es nicht einfach so offen in der Datei herumliegen lassen (so wie der Herr Schlosser das auch heute angesprochen hat).

**Comment by a71na** [comment]
Anmeldedaten habt ihr beide per Mail erhalten.

**Comment by a71na** [comment]
Als kleines Update: Encryption funktioniert jetzt bei uns

**Comment by 12Jacky** [comment]
Ich habe mir das Ticket angeschaut und versuche es momentan ein zubinden. Pushe es aber solange nicht bis ich die Encryption eingerichtet habe. Auch habe ich momentan noch eine Fehlermeldung, die ich mir am Montag genauer anschaue. Sobald es funktioniert pushe und commite ich

**Comment by 12Jacky** [comment]
Ich habe die Datenbank jetzt vollständig integriert, sie kann Daten ziehen, das einzige ist wenn der Code verwendet wird muss der Benutzer seinen eigenen Benutzer als auch sein Verschlüsseltes Passwort verwenden. Sonst ist der Code nicht ausführbar.
