### ISSUE TITLE
Testumfrage Team 1 bereitstellen

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#62]
Testumfrage mit Fragen zu z.B jeweils 3 Radio-Buttons, 3 Checkbox-Buttons und 3 Open Text Responses
Bis Dienstag 11.06
Word/SQL

**Comment by a71na** [comment]
#19 => Das widerspricht sich etwas. Abgemacht war, dass ihr eine Testumfrage erstellt, während wir uns um die cloud-basierte Datenbank kümmern.

**Comment by 12Jacky** [comment]
[Fragebogen-für-Team-2.txt](https://github.com/user-attachments/files/15778381/Fragebogen-fur-Team-2.txt)

**Comment by 12Jacky** [comment]
[Fragebogen-für-Team-2.txt](https://github.com/user-attachments/files/15778645/Fragebogen-fur-Team-2.txt)

Jetzt sollten bei allen Fragen die 10 Antwortoptionen da sein, @a71na hoffe es passt so☺️

**Comment by a71na** [comment]
So sieht es bisher in unserem Editor aus :)
![grafik](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/166111939/721ebf05-1f9f-4e80-9b51-160de71ef6ca)
