### ISSUE TITLE
HTML Darstellung

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#64]
Lokale HTML Darstellung von der Analyse

**Comment by 12Jacky** [comment]
Anforderungen: 
Die HTML soll unter den Button 
![image](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/166836065/1a0e1336-871a-402d-8e26-13b5146fb7a7)
gefunden werden.
Es sollen auf der Seite die Diagramme und Fragen angezeigt werden.

**Comment by 12Jacky** [comment]
Ist zu groß, deswegen mache ich mehrere kleine Teil Tickets daraus
