### ISSUE TITLE
Integration zu Umfrage Plattform

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#65]
1. Team-Plattform erstellt Branch für Team-Analyse @a71na (erledigt am 14.06.2024 - Branch heißt R-integration)
2. Team-Plattform hilft bei Setup von Spring-Boot-Server, wenn notwendig @a71na 
3. Team-Analyse muss eine Schnittstelle zwischen Java und R erstellen, am besten in eigener Klasse @Abdullah-C58 
5. Team-Plattform stellt Datenbank online zur Verfügung (breites erledigt von @a71na) siehe Wiki
6. Team-Analyse muss eine HTML-Seite zur Anzeige der Analyse erstellen @12Jacky (Rückfragen an @BenVonRuehrei )

Zu erledigen bis 21.06.2024

**Comment by 12Jacky** [comment]
Die Integration der HTML Seite war erfolgreich. Auch die Punkte vom BenVonRuehrei und a71na sind abgeschlossen. Es fehlt nur noch der Punkt 3.

**Comment by 12Jacky** [comment]
Ich habe für mich eine super lösung gefunden, das die Schnittstelle super funktioniert. Damit schließe ich das Ticket
