### ISSUE TITLE
Bildliche Darstellung machen für die Website

### ISSUE THREAD

**Issue by Abdullah-C58** [IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii#9]
Wie soll die Analyse angezeigt werden? Wie viele Charts, Diagramme etc.

**Comment by 12Jacky** [comment]
Auf die Webseite der Anderen und dafür brauchen wir die Absprache

**Comment by 12Jacky** [comment]
Ja denke sowas zählt da rein. Aber falls wir es brauchen können wir es immer noch irgendwann machen

**Comment by 12Jacky** [comment]
Ich habe das nicht mit Figma gemacht, da es zu komplex wäre, ich habe es einfach händisch aufgezeichnet.

![image](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-daten-analyse-thema-ii/assets/166836065/9cf451d4-9ed2-41a4-a3df-6f8bf4d287f3)
